version: '3'

services:
  web:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test+4304+"
      POSTGRES_DB: "test_bulk"
