version: '3'
services:
  postgres:
    image: "postgres:latest"
    command: postgres -c log_statement=all
    ports:
      - "5486:5432"
    environment:
      - POSTGRES_USER=test-db
      - POSTGRES_PASSWORD=test+4304+
      - POSTGRES_DB=test-bulk
    volumes:
      - ./pg_data:/var/lib/postgresql/data/

  worker:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE=postgres
    depends_on:
      - postgres
    volumes:
      - .:/test

